services:
  mongodb:
    image: mongo:latest
    container_name: Api-Crud-Libros
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: libros
      MONGO_INITDB_ROOT_PASSWORD: api4321
    ports:
      - "27019:27017"
    volumes:
      - ./mongodb_data:/data/db
